version: '3.8'
services:
  nestjs-db:
    image: postgres:15.4
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456@
      - POSTGRES_DB=improvenodejs
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  nestjs-db:
    driver: local